# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Book.destroy_all
Comment.destroy_all
User.destroy_all
puts "seeds destroyed"

puts "creating Users..."
user1 = User.create(first_name: 'McKinsey', last_name: 'Leckenby', email:"leckenbym11@gmail.com", password_digest: BCrypt::Password.create('mckinsey01'))


puts "Seeding books..."
book1 = Book.create(img_url: "https://images-na.ssl-images-amazon.com/images/I/41kjojdfsQL._SX310_BO1,204,203,200_.jpg", title: "Breasts and Eggs", author: "Mieko Kawakami", description: "Challenging every preconception about storytelling and prose style, mixing wry humor and riveting emotional depth, Kawakami is today one of Japan’s most important and best-selling writers. She exploded onto the cultural scene first as a musician, then as a poet and popular blogger, and is now an award-winning novelist.", pages: "448", genre: "Literary fiction")
book2 = Book.create(img_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1628791882l/1232._SY475_.jpg", title: "The Shadow of the Wind", author: "Carlos Ruiz Zafón", description: "Barcelona, 1945: A city slowly heals from its war wounds, and Daniel, an antiquarian book dealer's son who mourns the loss of his mother, finds solace in a mysterious book entitled The Shadow of the Wind, by one Julian Carax. But when he sets out to find the author's other works, he makes a shocking discovery: someone has been systematically destroying every copy of every book Carax has written. In fact, Daniel may have the last of Carax's books in existence. Soon Daniel's seemingly innocent quest opens a door into one of Barcelona's darkest secrets--an epic story of murder, madness, and doomed love.", pages: "487", genre: "Historical fiction")
book3 = Book.create(img_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1410981835l/22929741.jpg", title: "The Argonauts", author: "Maggie Nelson", description: "Maggie Nelson's The Argonauts is a genre-bending memoir, a work of 'autotheory' offering fresh, fierce, and timely thinking about desire, identity, and the limitations and possibilities of love and language. At its center is a romance: the story of the author's relationship with the artist Harry Dodge. This story, which includes Nelson's account of falling in love with Dodge, who is fluidly gendered, as well as her journey to and through a pregnancy, offers a firsthand account of the complexities and joys of (queer) family-making.", pages: "160", genre: "Nonfiction")
book4 = Book.create(img_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1351500256l/89213.jpg", title: "Close to the Knives", author: "David Wojnarowicz", description: "In Close to the Knives, David Wojnarowicz gives us an important and timely document: a collection of creative essays - a scathing, sexy, sublimely humorous and honest personal testimony to the 'Fear of Diversity in America' From the author's violent childhood in suburbia to eventual homelessness on the streets and piers of New York City, to recognition as one of the most provocative artists of his generation -- Close to the Knives is his powerful and iconoclastic memoir. Street life, drugs, art and nature, family, AIDS, politics, friendship and acceptance: Wojnarowicz challenges us to examine our lives -- politically, socially, emotionally, and aesthetically", pages: "288", genre: "Nonfiction")
book5 = Book.create(img_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1540217136l/16160797.jpg", title: "The Cuckoo's Calling", author: "Robert Galbraith", description: "After losing his leg to a land mine in Afghanistan, Cormoran Strike is barely scraping by as a private investigator. Then John Bristow walks through his door with an amazing story: His sister, the legendary supermodel Lula Landry, famously fell to her death a few months earlier. The police ruled it a suicide, but John refuses to believe that. The case plunges Strike into the world of multimillionaire beauties, rock-star boyfriends, and desperate designers, and it introduces him to every variety of pleasure, enticement, seduction, and delusion known to man", pages: "456", genre: "Mystery")
book6 = Book.create(img_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1364848759l/346404.jpg", title: "Queer Street: Rise and Fall of an American Culture, 1947-1985", author: "James McCourt", description: "A fierce critical intelligence animates every page of Queer Street. Its sentences are dizzying divagations. The postwar generation of queer New York has found a sophisticated bard singing 'the elders' history' (The New York Times). James McCourt's seminal Queer Street has proven unrivaled in its ability to capture the voices of a mad, bygone era. Beginning with the influx of liberated veterans into downtown New York and barreling through four decades of crisis and triumph up to the era of the floodtide of AIDS, McCourt positions his own exhilarating experience against the whirlwind history of the era. The result is a commanding and persuasive interlocking of personal, intellectual, and social history that will be read, dissected, and honored as the masterpiece it is for decades to come. A Publishers Weekly Best Book of 2003; a Lambda Award finalist.", pages: "592", genre: "LGBT > Queer")
book7 = Book.create(img_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1631519495l/6289283._SY475_.jpg", title: "Born to Run: A Hidden Tribe, Superathletes, and the Greatest Race the World Has Never Seen", author: "Christopher McDougall", description: "Full of incredible characters, amazing athletic achievements, cutting-edge science, and, most of all, pure inspiration, Born to Run is an epic adventure that began with one simple question: Why does my foot hurt? In search of an answer, Christopher McDougall sets off to find a tribe of the world’s greatest distance runners and learn their secrets, and in the process shows us that everything we thought we knew about running is wrong.", pages: "287", genre: "Nonfiction")
book8 = Book.create(img_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1513713760l/36820477.jpg", title: "The Cost of Living", author: "Deborah Levy", description: "The Cost of Living explores the subtle erasure of women's names, spaces, and stories in the modern everyday. In this “living autobiography” infused with warmth and humor, Deborah Levy critiques the roles that society assigns to us, and reflects on the politics of breaking with the usual gendered rituals. What does it cost a woman to unsettle old boundaries and collapse the social hierarchies that make her a minor character in a world not arranged to her advantage?", pages: "144", genre: "Nonfiction")
book9 = Book.create(img_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1577478589l/49994260._SY475_.jpg", title: "Limitless: Upgrade Your Brain, Learn Anything Faster, and Unlock Your Exceptional Life", author: "Jim Kwik", description: "For the last 25 years, Jim Kwik has helped everyone from celebrities to CEOs to students improve their memory, increase their decision-making skills, learn to speed-read, and unleash their superbrains.", pages: "343", genre: "Self Help")
book10 = Book.create(img_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1467260965l/206236._SY475_.jpg", title: "The Power of the Dog", author: "Don Winslow", description: "This novel of the drug trade takes you deep inside a world riddled with corruption, betrayal, and bloody revenge. Art Montana is an obsessive DEA agent. The Barrera brothers are heirs to a drug empire. Nora Hayden is a jaded teenager who becomes a high-class hooker. Father Parada is a powerful and incorruptible Catholic priest. Callan is an Irish kid from Hell’s Kitchen who grows up to be a merciless hitman. And they are all trapped in the world of the Mexican drug Federaci. From the streets of New York City to Mexico City and Tijuana to the jungles of Central America, this is the war on drugs like you’ve never seen it.", pages: "542", genre: "Mystery > Crime")



puts "Seeding comments..."
comment1 = Comment.create(user_id: user1.id, book_id: book1.id, comment: "Riveting")
comment2 = Comment.create(user_id: user1.id, book_id: book2.id, comment: "Good soup")
comment3 = Comment.create(user_id: user1.id, book_id: book2.id, comment: "My favorite book to this day, such an easy light read")
comment4 = Comment.create(user_id: user1.id, book_id: book3.id, comment: "Profound and intentional")
comment5 = Comment.create(user_id: user1.id, book_id: book3.id, comment: "I love Maggie's work - always discover new messages when reread")
comment6 = Comment.create(user_id: user1.id, book_id: book1.id, comment: "Had been wanting this translation and did not disappoint")
comment7 = Comment.create(user_id: user1.id, book_id: book4.id, comment: "Thoroughly enjoy what I understand of this book - hehe")

puts "done seeding"